development:
  adapter: postgresql
  database: harpr_dev
  host: localhost

test:
  adapter: postgresql
  database: harpr_test
  host: localhost

# production:
#   adapter: postgresql
#   database: revelation_production
#   host: localhost
#   username: pgsql
#   password: password
